Flexbe hfsmbth v2
ros-wg-delib/roscon24-workshop pull request #57
Opened 2024-10-08 02:52 UTC by dcconner

- update license
- add demo of the "mythical HFSMBTH" using BT.cpp
  - Required change to `pyrobosim_btcpp` to export headers

2024-10-08 03:25 UTC, dcconner commented
@facontidavide I asked for your review mainl because this requires a change to your CMakeLists.txt (included)

You may have input on how I implemented the custom BT executor.
(It does include some unnecessarily verbose status message for demo.)

Additionally, when I was trying to run with Groot2 in the Docker container, the default port is 5555 on startup, where the default port in code was 1667 (which I think is your standard).  

What's up with that?
I think for shop we should match default.

Also, I'm getting 

```
"Reply timeout"
socket disconnected
Warning: Tue Oct 8 02:35:03 2024 - Disconnected with error:  "Reply timeout" ,
 Reconnecting...
subscribe finished
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'LoopDouble' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'LoopString' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Script' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'ScriptCondition' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'SetBlackboard' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Switch2' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Switch3' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Switch4' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Switch5' is builtin model and is being overriden...."
Info: Tue Oct 8 02:35:03 2024 - "Error loading  model" "The model 'Switch6' is builtin model and is being overriden...."
```

which I don't recall seeing in earlier testing.

2024-10-09 23:54 UTC, sea-bass reviewed
This is extremely cool!

Left some small comments, but will let @facontidavide chime in with the modifications and give the final approve.

![image](https://github.com/user-attachments/assets/66a39866-4365-47c3-81cb-1a8f7e794ff9)

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/README.md
> +* `run_btcpp_tree_state.py` - Run a behavior tree using custom BehaviorTree.CPP v4 executor
IMO not needed to specify `v4`, as the convention is that is the latest, and if you're on the older versions you specify it.

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/docs/hfsmbth.md
> +# The Mythical HFSMBTH
Might want to fully define this once as Hierarchical Finite-State Machine / Behavior Tree Hybrid.

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/docs/hfsmbth.md
> +## BehaviorTree.cpp Hybrid Demo
following official tool name styling

```suggestion
## BehaviorTree.CPP Hybrid Demo

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/docs/hfsmbth.md
> +BT.cpp v4-based behavior trees using an `ExecuteTree` action server interface.
same comments as before, you can say BT.CPP (all caps) and omit the v4

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/config/pyrobosim_flexbe_btcpp.yaml
> +#      - btcpp_ros2_samples/bt_plugins
can this be removed if not used?

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/src/flexbe_btcpp_executor.cpp
> +  uint32_t tic_count_;
nit: the term used is "tick", so would prefer `tick_count_`.

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/src/flexbe_btcpp_executor.cpp
> +  rclcpp::Subscription<pyrobosim_msgs::msg::RobotState>::SharedPtr sub_;
nit: personal preference, but I like to call these variables by what they subscribe to, e.g., `state_sub_` or `robot_state_sub_`.

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/trees/problem1.xml
> +        <Sequence name="DetecSnackBackToPantry">
I think I had this comment in the original BT.CPP PR, but

```suggestion
        <Sequence name="DetectSnackBackToPantry">

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/docs/hfsmbth.md
> +    This uses a `RunBtCppTreeState` to send `ExecuteTree` action goals to the custom `flexbe_btcpp_executor` node.
Is this extra spacing at the start of the line intentional?

2024-10-09 23:54 UTC, sea-bass commented on technologies/FlexBE/docs/hfsmbth.md
> +You may optionally start `groot2` to visualize the behavior tree as it executes.
suggest showing the command

```bash
./Groot2.AppImage
```

2024-10-10 01:57 UTC, dcconner commented
thanks for comments; cleaning them up was more fun than grading my AI midterm :-)

2024-10-13 15:08 UTC, facontidavide commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/src/flexbe_btcpp_executor.cpp
> +
you might wany to add  `IsBatteryLow` and `IsBatteryFull`, too

2024-10-13 15:09 UTC, facontidavide commented
very nice! just a minor comment!

2024-10-13 15:11 UTC, facontidavide requested changes

2024-10-13 15:11 UTC, facontidavide commented on technologies/FlexBE/pyrobosim_flexbe_btcpp/config/pyrobosim_flexbe_btcpp.yaml
> +    groot2_port: 1667 # Optional (defaults to 1667)
```suggestion
    groot2_port: 5555
```

Change to use the same default as Groot2

2024-10-13 15:13 UTC, facontidavide commented
![image](https://github.com/user-attachments/assets/9061c378-a4da-4521-9022-3b136814b64d)

2024-10-14 01:42 UTC, dcconner commented
addressed @facontidavide comments and had to move BehaviorTree.CPP to latest humble branch that includes fix to issue that is required for this demo.

Apparently a merge undid that prior fix.

2024-10-14 14:05 UTC, sea-bass approved these changes
The comments all seem to be addressed ✅

2024-10-14 15:57 UTC, merged