Add simple BT.CPP solutions to Problems 2 and 3
ros-wg-delib/roscon24-workshop pull request #72
Opened 2024-10-17 01:15 UTC by sea-bass

This PR:
* Fixes the Problem 2 solution
* Adds a really, really, really bad (but working) solution to Problem 3
* Adds a barely functional attempt at Problem 4 in which I do a reactive sequence to navigate locations until the battery is low. I am hitting a segfault when the battery crosses the threshold, so thought I would share.

2024-10-18 15:41 UTC, facontidavide commented
Thanks a lot @sea-bass . Do we want to give th full solution to everyone. isn't this supposed to be an excercise?

2024-10-18 16:01 UTC, matthias-mayr commented
> Thanks a lot @sea-bass . Do we want to give th full solution to everyone. isn't this supposed to be an excercise?

At least I voted for providing solutions as well. If people want to cheat, I don't care - they are here voluntarily. Maybe some people get severely stuck and need a good indication on where to go.

At least for SkiROS2, the later problems should also build on earlier ones, so if someone was not able to solve p1 or p2, I want them to be able to hop back in and copy the solutions from previous problems.

2024-10-18 16:18 UTC, sea-bass commented
Agree with @matthias-mayr -- these are the solution trees. Presumably the workshop will involve opening up Groot and building these from scratch, but referring to these XMLs as/if needed.

2024-10-18 18:41 UTC, ct2034 commented
I was thinking like you before, @facontidavide. 
But now I also like the idea of treating the participants as adults and my convince stuff also contains the full solutions.

2024-10-19 05:54 UTC, ct2034 commented
> I was thinking like you before, @facontidavide. But now I also like the idea of treating the participants as adults and my convince stuff also contains the full solutions.

However, maybe we could move them to another folder. Something like `solutions`. Because right now, the readme suggests creating your trees in the `technologies/BehaviorTree.CPP/pyrobosim_btcpp/trees` folder. But when the participants navigate there, they find all the solutions and then their work may feel a bit pointless, I guess.

2024-10-19 06:53 UTC, ct2034 requested changes

2024-10-19 06:53 UTC, ct2034 commented on technologies/BehaviorTree.CPP/README.md
I suggest to change line 12 from
```
colcon build --symlink-install --packages-select pyrobosim_btcpp
```
to
```
colcon build --symlink-install --packages-up-to pyrobosim_btcpp
```
to also work if nothing is build so far.

2024-10-19 06:53 UTC, ct2034 commented on technologies/BehaviorTree.CPP/pyrobosim_btcpp/trees/problem3.xml
Worked for me after a couple of tries. We could consider increasing the attempts. I think pick and place have a 0.5 success probability. This can still after 5 retries easily.

2024-10-19 06:53 UTC, ct2034 commented on technologies/BehaviorTree.CPP/pyrobosim_btcpp/trees/problem4.xml
This failed for me, because the door to the charger is still closed. Is this intended?

2024-10-19 06:55 UTC, ct2034 commented on technologies/BehaviorTree.CPP/README.md
as is said in https://github.com/ros-wg-delib/roscon24-workshop/pull/72#issuecomment-2423586870, I would suggest to move the solutions to a separate folder.

2024-10-19 07:09 UTC, ct2034 commented on technologies/BehaviorTree.CPP/pyrobosim_btcpp/trees/problem4.xml
And yes, I also experience the segfault sometimes.

2024-10-19 07:17 UTC, sea-bass commented on technologies/BehaviorTree.CPP/pyrobosim_btcpp/trees/problem4.xml
Yes, I did not spend much time at all to get this working. Should probably delete this file for now

2024-10-19 20:22 UTC, sea-bass commented
All PR comments implemented, and I got an (almost fully) working Problem 4 solution!

2024-10-19 20:28 UTC, sea-bass commented
@facontidavide I am getting sporadic errors canceling the Navigate action when the battery going low coincides with that... I'm not 100% sure if the bug is on PyRoboSim or BT.CPP end, since the FlexBE and ros_bt_py examples cancel properly, as do my unit tests.

2024-10-19 20:50 UTC, ct2034 commented
I am at the airport waiting for the plane from Abu Dhabi to Copenhagen. So I will not be able to look at this for the next 12h. ;)
________________________________
From: Sebastian Castro ***@***.***>
Sent: Sunday, October 20, 2024 12:28:27 AM
To: ros-wg-delib/roscon24-workshop ***@***.***>
Cc: Henkel Christian (CR/ASD1) ***@***.***>; Review requested ***@***.***>
Subject: Re: [ros-wg-delib/roscon24-workshop] Add simple BT.CPP solutions to Problems 2 and 3 (PR #72)


@facontidavide<https://github.com/facontidavide> I am getting sporadic errors canceling the Navigate action when the battery going low coincides with that... I'm not 100% sure if the bug is on PyRoboSim or BT.CPP end, since the FlexBE and ros_bt_py examples cancel properly, as do my unit tests.

—
Reply to this email directly, view it on GitHub<https://github.com/ros-wg-delib/roscon24-workshop/pull/72#issuecomment-2424196718>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABVHERPZHCMRGFP4M5YDEYTZ4K6GXAVCNFSM6AAAAABQCUIWROVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRUGE4TMNZRHA>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-10-20 07:53 UTC, merged

2024-10-20 08:29 UTC, facontidavide commented
I too the liberty to push directly to main some cleanup of problem 1 and 2.
d6b85318de674c061decda41dc153b5e840754d6

Thanks a lot!!!

2024-11-05 13:59 UTC, ct2034 commented
Hi humans

Following our discussion about the paper yesterday, I have created a repo under https://github.com/ros-wg-delib/workshop-survey-paper. All members of the org should have access, and those of you who were not members should have an invitation. Please let me know if you have trouble with the access. The repo only contains the data right now and a script to explore it with seaborn. Feel free to poke around and let me know what you find.

Regarding the venue, I was talking to Ingo, who recommended against the RoSE workshop mainly due to its limited size, and he was also not happy with the publication of the results. This now of course buys some time for us. After the discussion with him, we are left with https://joss.theoj.org/ and https://www.ieee-ras.org/publications/ra-p.  I would see the main difference in the focus of SW eng for JOSS and Robotics for RA-P. But I think that our results are probably more interesting for the later audience, and would therefore argue for RA-P. I think also it would be fun to a newer venue that is expected to increase in popularity soon. If you are happy with that assessment, I can also start to include the IEEE template in the repo and start writing.

Cheers
Christian

---

Christian Henkel

Software Engineering (CR/ASD1)
Robert Bosch GmbH | Renningen | 70465 Stuttgart | GERMANY | www.bosch.com
Mobile +49 173 5408283 | ***@***.******@***.***>

Registered Office: Stuttgart, Registration Court: Amtsgericht Stuttgart, HRB 14000;
Chairman of the Supervisory Board: Prof. Dr. Stefan Asenkerschbaumer; Managing Directors: Dr. Stefan Hartung,
Dr. Christian Fischer, Filiz Albrecht, Dr. Markus Forschner, Dr. Markus Heyn, Rolf Najork